apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"
  Jwt__Issuer: "FCG"
  Jwt__Audience: "FCG"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: "/"
  RabbitMq__PaymentProcessedQueue: "catalog-payment-processed"
