apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  ConnectionStrings__CatalogDatabase: "Server=sql-server,1433;Database=FcgCatalogDb;User Id=sa;Password=<sql-password>;TrustServerCertificate=True"
  Jwt__Key: "<same-32-byte-or-longer-key-used-by-users-api>"
  RabbitMq__Username: "<rabbitmq-username>"
  RabbitMq__Password: "<rabbitmq-password>"
